from __future__ import annotations

import functools
import importlib.util
import marshal
import types
from pathlib import Path
from typing import Any


@functools.lru_cache(maxsize=4)
def _load_parser_module_cached(
    canonical_path: str,
    modification_time_ns: int,
    file_size: int,
) -> types.ModuleType:
    """Load and execute a CPython bytecode module once per file version.

    ``modification_time_ns`` and ``file_size`` are deliberately part of the
    cache key. Replacing the parser file therefore causes a new module to be
    loaded without requiring explicit cache invalidation.

    The parser file is assumed to be a contemporary CPython ``.pyc`` file
    with a 16-byte header.
    """
    del modification_time_ns, file_size  # Used exclusively as cache-key data.

    path = Path(canonical_path)

    with path.open("rb") as stream:
        header = stream.read(16)

        if len(header) != 16:
            raise ImportError(f"Truncated parser bytecode file: {path}")

        if header[:4] != importlib.util.MAGIC_NUMBER:
            raise ImportError(
                f"Incompatible parser bytecode: {path}. "
                "The parser was probably generated by a different "
                "CPython version."
            )

        # Unlike read_bytes()[16:], this does not create a sliced copy of the
        # complete serialized code object.
        code = marshal.load(stream)

    if not isinstance(code, types.CodeType):
        raise ImportError(f"Parser does not contain a module code object: {path}")

    module_name = f"_embedded_gamedata_{abs(hash(canonical_path)):x}"
    module = types.ModuleType(module_name)
    module.__file__ = canonical_path
    module.__package__ = ""
    module.__loader__ = None

    exec(code, module.__dict__)

    if not callable(getattr(module, "parse_typed", None)):
        raise ImportError(f"Parser does not define parse_typed(): {path}")

    if not callable(getattr(module, "parse_byte", None)):
        raise ImportError(f"Parser does not define parse_byte(): {path}")

    return module


def _load_parser_module(path: Path) -> types.ModuleType:
    """Return the cached parser module corresponding to the current file."""
    canonical_path = path.resolve(strict=True)
    stat = canonical_path.stat()

    return _load_parser_module_cached(
        str(canonical_path),
        stat.st_mtime_ns,
        stat.st_size,
    )


class CatalogResolver:
    """Resolve catalog identifiers without modifying installed game data."""

    _NAME_FIELDS = (
        "StringName",
        "Name",
        "StringTitle",
        "StringID",
    )

    _CATALOG_FILENAMES = (
        "It",
        "ItArti",
        "ItemGS",
        "ItRelic",
        "CharCostume",
        "ItemTitle",
        "ItemProfile",
        "ItemEmoticon",
        "ChHunt",
        "ChShad",
        "Achi",
    )

    def __init__(self, parser_path: Path) -> None:
        self._parser_path = parser_path
        self.names: dict[int, str] = {}
        self.names_by_file: dict[str, dict[int, str]] = {}
        self.level_curve: dict[int, int] = {}

    def load(self, game_data_directory: Path) -> None:
        if not self._parser_path.is_file():
            raise FileNotFoundError(
                f"Game-data parser not found: {self._parser_path}"
            )

        if not game_data_directory.is_dir():
            raise NotADirectoryError(
                f"GameData directory not found: {game_data_directory}"
            )

        # First invocation: load, deserialize, and execute.
        # Subsequent invocations: dictionary/cache lookup plus stat().
        module = _load_parser_module(self._parser_path)

        text_columns, _ = module.parse_typed(
            str(game_data_directory / "TextData.byte")
        )

        string_ids = text_columns["StringID"]
        translated_values = text_columns.get("Value_eng")
        if translated_values is None:
            translated_values = text_columns["Value"]

        translations = dict(
            zip(string_ids, translated_values, strict=False)
        )

        # Build new state instead of retaining stale entries if load() is
        # invoked multiple times on the same resolver.
        merged_names: dict[int, str] = {}
        names_by_file: dict[str, dict[int, str]] = {}

        self.level_curve = self._read_level_curve(
            module,
            game_data_directory,
        )

        parse_typed = module.parse_typed
        translate = translations.get

        for filename in self._CATALOG_FILENAMES:
            try:
                columns, _ = parse_typed(
                    str(game_data_directory / f"{filename}.byte")
                )
            except (OSError, ValueError, KeyError):
                continue

            item_ids = columns.get("ID", ())
            name_columns = tuple(
                columns.get(field, ())
                for field in self._NAME_FIELDS
            )

            file_names: dict[int, str] = {}

            for index, item_id in enumerate(item_ids):
                if not isinstance(item_id, int):
                    continue

                for values in name_columns:
                    if index >= len(values):
                        continue

                    value = values[index]
                    if not isinstance(value, str) or not value:
                        continue

                    resolved = translate(value, value)
                    file_names.setdefault(item_id, resolved)
                    merged_names.setdefault(item_id, resolved)
                    break

            names_by_file[filename] = file_names

        self.names = merged_names
        self.names_by_file = names_by_file

    def name(self, item_id: Any) -> str:
        return self.names.get(item_id, f"ID {item_id}")

    def name_in(
        self,
        filenames: tuple[str, ...],
        item_id: Any,
    ) -> str | None:
        """Resolve an ID only within the specified catalog namespaces."""
        if not isinstance(item_id, int):
            return None

        for filename in filenames:
            resolved = self.names_by_file.get(filename, {}).get(item_id)
            if resolved is not None:
                return resolved

        return None

    @staticmethod
    def _read_level_curve(
        module: types.ModuleType,
        game_data_directory: Path,
    ) -> dict[int, int]:
        """Read ``{level: cumulative TotalExp}`` from ChSJWLv.byte."""
        try:
            columns, _ = module.parse_byte(
                str(game_data_directory / "ChSJWLv.byte")
            )
            levels = columns["Level"]
            totals = columns["TotalExp"]
        except (OSError, ValueError, KeyError):
            return {}

        return {
            level: total
            for level, total in zip(levels, totals, strict=False)
            if isinstance(level, int) and isinstance(total, int)
        }
